//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string ItemId { get; set; }
        public string ISBN { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public string AuthorId { get; set; }
        public string PublisherId { get; set; }
        public Nullable<int> CopiesAvailable { get; set; }
        public Nullable<int> CopieOnLoan { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
